name: Unit Tests

on:
  push:
    branches: [ "main" ]           # consider: ["**"] to run on feature branches too
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: >
          dotnet test
          --no-build
          --configuration Release
          --verbosity normal
          --logger "trx;LogFileName=test_results.trx"
          --results-directory ./TestResults
          --collect "XPlat Code Coverage"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            TestResults/**/*.trx
            TestResults/**/coverage.cobertura.xml
          if-no-files-found: ignore
